/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.c                                                */
/*  DATE        :Fri, Nov 07, 2003                                     */
/*  DESCRIPTION :Program of sbrk                                       */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include <stddef.h>
//#include <stdio.h>
#include "sbrk.h"

//const size_t _sbrk_size=		/* Specifies the minimum unit of	*/
					/* the defined heap area		*/

extern char *_s1ptr;
extern int _freeptr;

#pragma pack 4
union HEAP_TYPE {
    long  dummy ;		/* Dummy for 4-byte boundary			*/
    char heap[HEAPSIZE];	/* Declaration of the area managed by sbrk	*/
};

#pragma section HEAP
static union HEAP_TYPE heap_area ;
#pragma section
#pragma unpack

/* End address allocated by sbrk	*/
static char *brk;
void init_sbrk()
{
	brk = (char *)&heap_area;
//	_freeptr = (int)heap_area.heap;
}

/**************************************************************************/
/*     sbrk:Memory area allocation                                        */
/*          Return value:Start address of allocated area (Pass)           */
/*                       -1                              (Failure)        */
/**************************************************************************/
char  *sbrk( int size )			/* Assigned area size	*/
{
      char  *p;

	if( brk + size > heap_area.heap + HEAPSIZE ) {	/* Empty area size	*/
		while (1);
		return (char *)-1;
	}

	p = brk;					/* Area assignment	*/
	brk += size;				/* End address update	*/
	return p;
}

