/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Mon, Mar 14, 2005                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
//#define HEAPSIZE 0x1a80000
#define   HEAPSIZE 0x800000
