################################################
# Make file generated by HEW
#

################################################################################################
# This make file contains one or more projects which contain one or more configurations.
# You can use the following user defines to describe the build you wish to have performed
# (user defines can be specified on the hmake command line using the syntax "<define>=<value>").
#
# PROJECT: Set to the name of the project you wish to build. If this define is not specified
#          or if it is set to "ALL" then all projects in the make file will be built.
#
# CONFIG: Can be used to specify the configuration which you want built inside of all the 
#         projects which are to be built. If no configuration related defines (see below) are 
#         specified or if CONFIG is set to "ALL", all configurations will be built.
#
# LIBM2DECCONFIG: Can be used to specify the configurations you wish to have built for the 
#              libm2dec project. If it is set to "ALL" then all configurations will be built.
#
# H264DECCONFIG: Can be used to specify the configurations you wish to have built for the 
#              h264dec project. If it is set to "ALL" then all configurations will be built.
#

!IF "$(PROJECT)" == ""
PROJECT = ALL
!MESSAGE No project given. Will build all projects.
!ENDIF

!IF "$(CONFIG)" == "" && "$(H264DECCONFIG)" == "" && "$(LIBM2DECCONFIG)" == ""
CONFIG = ALL
!MESSAGE No project given. Will build all projects.
!ENDIF

############################
# Toolchain directory define
# If incorrect, change to the location of the SuperH RISC engine Standard Toolchain toolchain
TC_INSTALL_DIR = c:\program files (x86)\renesas\hew\tools\renesas\sh\9_3_2

# libm2dec project
!IF "$(PROJECT)" == "ALL" || "$(PROJECT)" == "libm2dec"

# Release configuration
!IF  "$(CONFIG)" == "ALL" || "$(CONFIG)" == "Release" || "$(LIBM2DECCONFIG)" == "ALL" || "$(LIBM2DECCONFIG)" == "Release"

#####################################################
#
# Details:
#   Project: libm2dec
#   Configuration: Release
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin

# Renesas SH C/C++ Compiler02 phase

LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE=shc.exe
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0="..\libm2dec\Release\bitio.src"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC0="$(TC_INSTALL_DIR)\include\stlport\string.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1="..\libm2dec\Release\h264.src"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1="$(TC_INSTALL_DIR)\include\stlport\assert.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2="..\libm2dec\Release\idct.src"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC2="..\..\..\src\lib\m2types.h" "..\..\..\src\lib\m2d_macro.h" "$(TC_INSTALL_DIR)\include\umachine.h" \
	"$(TC_INSTALL_DIR)\include\builtin.h" "..\..\..\src\lib\idct.h"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3="..\libm2dec\Release\m2d.src"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4="..\libm2dec\Release\motioncomp.src"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC4="..\..\..\src\lib\m2d_macro.h" "..\..\..\src\lib\m2types.h" "$(TC_INSTALL_DIR)\include\umachine.h" \
	"$(TC_INSTALL_DIR)\include\builtin.h" "..\..\..\src\lib\motioncomp.h"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5="..\libm2dec\Release\mpeg2.src"
LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC6="..\libm2dec\Release\mpeg_demux.src"

# Renesas SH Assembler03 phase

LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE=asmsh.exe
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC0="..\libm2dec\Release\idct_asm.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC1="..\libm2dec\Release\motioncomp_asm.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC2="..\libm2dec\Release\bitio.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC3="..\libm2dec\Release\h264.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC4="..\libm2dec\Release\idct.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC5="..\libm2dec\Release\m2d.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC6="..\libm2dec\Release\motioncomp.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC7="..\libm2dec\Release\mpeg2.obj"
LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC8="..\libm2dec\Release\mpeg_demux.obj"

# Renesas OptLinker04 phase

LIBM2DEC_RELEASE_OPTLINKER04_EXE=LnkSpawn.exe
LIBM2DEC_RELEASE_OPTLINKER04_INFILESC0="..\libm2dec\Release\bitio.obj" "..\libm2dec\Release\h264.obj" "..\libm2dec\Release\idct.obj" \
	"..\libm2dec\Release\idct_asm.obj" "..\libm2dec\Release\m2d.obj" "..\libm2dec\Release\motioncomp.obj" \
	"..\libm2dec\Release\motioncomp_asm.obj" "..\libm2dec\Release\mpeg2.obj" "..\libm2dec\Release\mpeg_demux.obj"
LIBM2DEC_RELEASE_OPTLINKER04_OUTFILESC0="..\libm2dec\Release\libm2dec.lib"

#######################
# nmake "all" statement

ALL:	LIBM2DEC_RELEASE_SH_CC_COMPILER02_ENVC0 \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0) \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1) \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2) \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3) \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4) \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5) \
	$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC6) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC0) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC1) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC2) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC3) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC4) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC5) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC6) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC7) \
	$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC8) \
	$(LIBM2DEC_RELEASE_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

LIBM2DEC_RELEASE_SH_CC_COMPILER02_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\minegisi\AppData\Local\Temp

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0) : "..\..\..\src\lib\bitio.c" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC0)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\bitio.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\bitio.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1) : "..\..\..\src\lib\h264.cpp" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\h264.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\h264.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2) : "..\..\..\src\lib\idct.cpp" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC2)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\idct.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\idct.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3) : "..\..\..\src\lib\m2d.cpp" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\m2d.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\m2d.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4) : "..\..\..\src\lib\motioncomp.cpp" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC4)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\motioncomp.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\motioncomp.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5) : "..\..\..\src\lib\mpeg2.cpp" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\mpeg2.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\mpeg2.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC6) : "..\..\..\src\lib\mpeg_demux.cpp" $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG
-code=asmcode
-object="..\libm2dec\Release\mpeg_demux.src"
-section=program=PM2D,const=CM2D
-speed
-inline=800
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\mpeg_demux.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas SH Assembler03 phase
!MESSAGE

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC0) : "..\..\..\src\lib\idct_asm.src"
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\..\..\src\lib\idct_asm.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\idct_asm.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC1) : "..\..\..\src\lib\motioncomp_asm.src"
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\..\..\src\lib\motioncomp_asm.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\motioncomp_asm.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC2) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\bitio.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\bitio.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC3) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\h264.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\h264.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC4) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\idct.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\idct.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC5) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\m2d.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\m2d.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC6) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\motioncomp.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\motioncomp.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC7) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\mpeg2.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\mpeg2.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_OUTFILESC8) : $(LIBM2DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC6)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Release\mpeg_demux.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-nodebug
-object="..\libm2dec\Release\mpeg_demux.obj"
-literal=pool,branch,jump,return
-nolist
-nologo
-chgincpath
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(LIBM2DEC_RELEASE_OPTLINKER04_OUTFILESC0) : $(LIBM2DEC_RELEASE_OPTLINKER04_INFILESC0)
	"$(LIBM2DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_RELEASE_OPTLINKER04_EXE)" -subcommand=<<
noprelink
form library
nomessage 
list "..\libm2dec\Release\libm2dec.lbp"
nologo
-input="..\libm2dec\Release\bitio.obj"
-input="..\libm2dec\Release\h264.obj"
-input="..\libm2dec\Release\idct.obj"
-input="..\libm2dec\Release\idct_asm.obj"
-input="..\libm2dec\Release\m2d.obj"
-input="..\libm2dec\Release\motioncomp.obj"
-input="..\libm2dec\Release\motioncomp_asm.obj"
-input="..\libm2dec\Release\mpeg2.obj"
-input="..\libm2dec\Release\mpeg_demux.obj"
output "..\libm2dec\Release\libm2dec.lib"
-exit
<<


!ENDIF

# Debug configuration
!IF  "$(CONFIG)" == "ALL" || "$(CONFIG)" == "Debug" || "$(LIBM2DECCONFIG)" == "ALL" || "$(LIBM2DECCONFIG)" == "Debug"

#####################################################
#
# Details:
#   Project: libm2dec
#   Configuration: Debug
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin

# Renesas SH C/C++ Compiler02 phase

LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE=shc.exe
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0="..\libm2dec\Debug\bitio.src"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC0="$(TC_INSTALL_DIR)\include\stlport\string.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1="..\libm2dec\Debug\h264.src"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1="$(TC_INSTALL_DIR)\include\stlport\assert.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2="..\libm2dec\Debug\idct.src"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC2="..\..\..\src\lib\m2types.h" "..\..\..\src\lib\m2d_macro.h" "$(TC_INSTALL_DIR)\include\umachine.h" \
	"$(TC_INSTALL_DIR)\include\builtin.h" "..\..\..\src\lib\idct.h" "$(TC_INSTALL_DIR)\include\stlport\string.h" \
	"$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3="..\libm2dec\Debug\m2d.src"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4="..\libm2dec\Debug\motioncomp.src"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC4="..\..\..\src\lib\m2d_macro.h" "..\..\..\src\lib\m2types.h" "$(TC_INSTALL_DIR)\include\umachine.h" \
	"$(TC_INSTALL_DIR)\include\builtin.h" "..\..\..\src\lib\motioncomp.h" "$(TC_INSTALL_DIR)\include\stlport\string.h" \
	"$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5="..\libm2dec\Debug\mpeg2.src"
LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC6="..\libm2dec\Debug\mpeg_demux.src"

# Renesas SH Assembler03 phase

LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE=asmsh.exe
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC0="..\libm2dec\Debug\idct_asm.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC1="..\libm2dec\Debug\motioncomp_asm.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC2="..\libm2dec\Debug\bitio.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC3="..\libm2dec\Debug\h264.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC4="..\libm2dec\Debug\idct.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC5="..\libm2dec\Debug\m2d.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC6="..\libm2dec\Debug\motioncomp.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC7="..\libm2dec\Debug\mpeg2.obj"
LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC8="..\libm2dec\Debug\mpeg_demux.obj"

# Renesas OptLinker04 phase

LIBM2DEC_DEBUG_OPTLINKER04_EXE=LnkSpawn.exe
LIBM2DEC_DEBUG_OPTLINKER04_INFILESC0="..\libm2dec\Debug\bitio.obj" "..\libm2dec\Debug\h264.obj" "..\libm2dec\Debug\idct.obj" \
	"..\libm2dec\Debug\idct_asm.obj" "..\libm2dec\Debug\m2d.obj" "..\libm2dec\Debug\motioncomp.obj" \
	"..\libm2dec\Debug\motioncomp_asm.obj" "..\libm2dec\Debug\mpeg2.obj" "..\libm2dec\Debug\mpeg_demux.obj"
LIBM2DEC_DEBUG_OPTLINKER04_OUTFILESC0="..\libm2dec\Debug\libm2dec.lib"

#######################
# nmake "all" statement

ALL:	LIBM2DEC_DEBUG_SH_CC_COMPILER02_ENVC0 \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0) \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1) \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2) \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3) \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4) \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5) \
	$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC6) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC0) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC1) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC2) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC3) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC4) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC5) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC6) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC7) \
	$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC8) \
	$(LIBM2DEC_DEBUG_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

LIBM2DEC_DEBUG_SH_CC_COMPILER02_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\minegisi\AppData\Local\Temp

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0) : "..\..\..\src\lib\bitio.c" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC0)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\bitio.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\bitio.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\bitio.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1) : "..\..\..\src\lib\h264.cpp" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\h264.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\h264.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\h264.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2) : "..\..\..\src\lib\idct.cpp" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC2)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\idct.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\idct.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\idct.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3) : "..\..\..\src\lib\m2d.cpp" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\m2d.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\m2d.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\m2d.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4) : "..\..\..\src\lib\motioncomp.cpp" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC4)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\motioncomp.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\motioncomp.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\motioncomp.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5) : "..\..\..\src\lib\mpeg2.cpp" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\mpeg2.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\mpeg2.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\mpeg2.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC6) : "..\..\..\src\lib\mpeg_demux.cpp" $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport"
-define=NDEBUG,UNIT_TEST
-code=asmcode
-object="..\libm2dec\Debug\mpeg_demux.src"
-debug
-section=program=PM2D,const=CM2D,data=DM2D,bss=BM2D
-listfile="..\libm2dec\Debug\mpeg_demux.lst"
-show=source
-speed
-inline=25
-gbr=auto
-macsave=0
-save_cont_reg=0
-loop
"..\..\..\src\lib\mpeg_demux.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas SH Assembler03 phase
!MESSAGE

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC0) : "..\..\..\src\lib\idct_asm.src"
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\..\..\src\lib\idct_asm.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\idct_asm.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\idct_asm.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC1) : "..\..\..\src\lib\motioncomp_asm.src"
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\..\..\src\lib\motioncomp_asm.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\motioncomp_asm.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\motioncomp_asm.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC2) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\bitio.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\bitio.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\bitio.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC3) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\h264.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\h264.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\h264.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC4) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\idct.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\idct.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\idct.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC5) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\m2d.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\m2d.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\m2d.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC6) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\motioncomp.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\motioncomp.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\motioncomp.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC7) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\mpeg2.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\mpeg2.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\mpeg2.lis"
-nologo
-chgincpath
<<

$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_OUTFILESC8) : $(LIBM2DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC6)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_SH_ASSEMBLER03_EXE)" -subcommand=<<
"..\libm2dec\Debug\mpeg_demux.src"
-cpu=sh4aldsp
-endian=little
-round=zero
-denormalize=off
-debug
-object="..\libm2dec\Debug\mpeg_demux.obj"
-literal=pool,branch,jump,return
-list="..\libm2dec\Debug\mpeg_demux.lis"
-nologo
-chgincpath
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(LIBM2DEC_DEBUG_OPTLINKER04_OUTFILESC0) : $(LIBM2DEC_DEBUG_OPTLINKER04_INFILESC0)
	"$(LIBM2DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(LIBM2DEC_DEBUG_OPTLINKER04_EXE)" -subcommand=<<
form library
nomessage 
list "..\libm2dec\Debug\libm2dec.lbp"
nologo
-input="..\libm2dec\Debug\bitio.obj"
-input="..\libm2dec\Debug\h264.obj"
-input="..\libm2dec\Debug\idct.obj"
-input="..\libm2dec\Debug\idct_asm.obj"
-input="..\libm2dec\Debug\m2d.obj"
-input="..\libm2dec\Debug\motioncomp.obj"
-input="..\libm2dec\Debug\motioncomp_asm.obj"
-input="..\libm2dec\Debug\mpeg2.obj"
-input="..\libm2dec\Debug\mpeg_demux.obj"
output "..\libm2dec\Debug\libm2dec.lib"
-exit
<<


!ENDIF

!ENDIF

# h264dec project
!IF "$(PROJECT)" == "ALL" || "$(PROJECT)" == "h264dec"

# Debug configuration
!IF  "$(CONFIG)" == "ALL" || "$(CONFIG)" == "Debug" || "$(H264DECCONFIG)" == "ALL" || "$(H264DECCONFIG)" == "Debug"

#####################################################
#
# Details:
#   Project: h264dec
#   Configuration: Debug
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin
H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0="..\h264dec\Debug\h264dec.lib"
H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0="$(TC_INSTALL_DIR)\bin\libinc.pak"

# Renesas SH C/C++ Compiler02 phase

H264DEC_DEBUG_SH_CC_COMPILER02_EXE=shc.exe
H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0="..\h264dec\Debug\resetprg.obj"
H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC0="$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" "$(TC_INSTALL_DIR)\include\stlport\string.h" \
	"$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1="..\h264dec\Debug\sbrk.obj"
H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1="$(TC_INSTALL_DIR)\include\stlport\stddef.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2="..\h264dec\Debug\h264dec.obj"
H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC2="$(TC_INSTALL_DIR)\include\stlport\assert.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3="..\h264dec\Debug\lowlevel.obj"
H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC3="$(TC_INSTALL_DIR)\include\stdlib.h" "$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\stdio.h" \
	"$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\umachine.h"
H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4="..\h264dec\Debug\md5.obj"
H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC4="..\..\..\src\app\md5.h" "$(TC_INSTALL_DIR)\include\stlport\string.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5="..\h264dec\Debug\my_getopt.obj"
H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC5="$(TC_INSTALL_DIR)\include\stdlib.h" "$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\stdio.h" \
	"$(TC_INSTALL_DIR)\include\string.h" "$(TC_INSTALL_DIR)\include\builtin.h" "..\..\..\src\app\my_getopt.h"

# Renesas SH Assembler03 phase

H264DEC_DEBUG_SH_ASSEMBLER03_EXE=asmsh.exe

# Renesas OptLinker04 phase

H264DEC_DEBUG_OPTLINKER04_EXE=LnkSpawn.exe
H264DEC_DEBUG_OPTLINKER04_INFILESC0="..\h264dec\Debug\h264dec.lib" "..\h264dec\Debug\h264dec.obj" "..\h264dec\Debug\lowlevel.obj" \
	"..\h264dec\Debug\md5.obj" "..\h264dec\Debug\my_getopt.obj" "..\h264dec\Debug\resetprg.obj" \
	"..\h264dec\Debug\sbrk.obj"
H264DEC_DEBUG_OPTLINKER04_OUTFILESC0="..\h264dec\Debug\h264dec.mot" "..\h264dec\Debug\h264dec.abs"
H264DEC_DEBUG_OPTLINKER04_DEPFILESC0="..\libm2dec\Debug\libm2dec.lib"

#######################
# nmake "all" statement

ALL:	H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_ENVC0 \
	$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0) \
	$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1) \
	$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2) \
	$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3) \
	$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4) \
	$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5) \
	$(H264DEC_DEBUG_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Library Generator01 phase
!MESSAGE

H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\minegisi\AppData\Local\Temp

$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) : $(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-output="..\h264dec\Debug\h264dec.lib"
-gbr=auto
-head=runtime,new,ctype,stdio,stdlib,string
<<

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC0) : "..\resetprg.c" $(H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC0)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\lib"
-object="..\h264dec\Debug\resetprg.obj"
-debug
-gbr=auto
"..\resetprg.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC1) : "..\sbrk.c" $(H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC1)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\lib"
-object="..\h264dec\Debug\sbrk.obj"
-debug
-gbr=auto
"..\sbrk.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC2) : "..\..\..\src\app\h264dec.cpp" $(H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC2)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Debug\h264dec.obj"
-debug
-gbr=auto
"..\..\..\src\app\h264dec.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC3) : "..\..\..\src\app\lowlevel.c" $(H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC3)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Debug\lowlevel.obj"
-debug
-gbr=auto
"..\..\..\src\app\lowlevel.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC4) : "..\..\..\src\app\md5.c" $(H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC4)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Debug\md5.obj"
-debug
-gbr=auto
"..\..\..\src\app\md5.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_DEBUG_SH_CC_COMPILER02_OUTFILESC5) : "..\..\..\src\app\my_getopt.c" $(H264DEC_DEBUG_SH_CC_COMPILER02_DEPFILESC5)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Debug\my_getopt.obj"
-debug
-gbr=auto
"..\..\..\src\app\my_getopt.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(H264DEC_DEBUG_OPTLINKER04_OUTFILESC0) : $(H264DEC_DEBUG_OPTLINKER04_INFILESC0) $(H264DEC_DEBUG_OPTLINKER04_DEPFILESC0)
	"$(H264DEC_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_DEBUG_OPTLINKER04_EXE)" -subcommand=<<
nomessage 
list "..\h264dec\Debug\h264dec.map"
show symbol,reference
nooptimize
-start=PBOOT,CBOOT/00,P,D,C,C$VTBL,CM2D,PM2D,PM2D_FAST,BM2D,B/0C000000,BHEAP/0C080000,BFILES/0D880000
nologo
-stack
-input="..\h264dec\Debug\h264dec.obj"
-input="..\h264dec\Debug\lowlevel.obj"
-input="..\h264dec\Debug\md5.obj"
-input="..\h264dec\Debug\my_getopt.obj"
-input="..\h264dec\Debug\resetprg.obj"
-input="..\h264dec\Debug\sbrk.obj"
-library="..\libm2dec\Debug\libm2dec.lib"
-library="..\h264dec\Debug\h264dec.lib"
-output="..\h264dec\Debug\h264dec.abs"
end
-input="..\h264dec\Debug\h264dec.abs"
form stype
output "..\h264dec\Debug\h264dec.mot"
-exit
<<


!ENDIF

# Release configuration
!IF  "$(CONFIG)" == "ALL" || "$(CONFIG)" == "Release" || "$(H264DECCONFIG)" == "ALL" || "$(H264DECCONFIG)" == "Release"

#####################################################
#
# Details:
#   Project: h264dec
#   Configuration: Release
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin
H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0="..\h264dec\Release\h264dec.lib"
H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0="$(TC_INSTALL_DIR)\bin\libinc.pak"

# Renesas SH C/C++ Compiler02 phase

H264DEC_RELEASE_SH_CC_COMPILER02_EXE=shc.exe
H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0="..\h264dec\Release\resetprg.obj"
H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC0="$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" "$(TC_INSTALL_DIR)\include\stlport\string.h" \
	"$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1="..\h264dec\Release\sbrk.obj"
H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1="$(TC_INSTALL_DIR)\include\stlport\stddef.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2="..\h264dec\Release\h264dec.obj"
H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC2="$(TC_INSTALL_DIR)\include\stlport\assert.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"
H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3="..\h264dec\Release\lowlevel.obj"
H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC3="$(TC_INSTALL_DIR)\include\stdlib.h" "$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\stdio.h" \
	"$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\umachine.h"
H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4="..\h264dec\Release\md5.obj"
H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC4="..\..\..\src\app\md5.h" "$(TC_INSTALL_DIR)\include\string.h" "$(TC_INSTALL_DIR)\include\stddef.h" \
	"$(TC_INSTALL_DIR)\include\builtin.h"
H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5="..\h264dec\Release\my_getopt.obj"
H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC5="$(TC_INSTALL_DIR)\include\stlport\stdlib.h" "$(TC_INSTALL_DIR)\include\stlport\stl\_cprolog.h"

# Renesas SH Assembler03 phase

H264DEC_RELEASE_SH_ASSEMBLER03_EXE=asmsh.exe

# Renesas OptLinker04 phase

H264DEC_RELEASE_OPTLINKER04_EXE=LnkSpawn.exe
H264DEC_RELEASE_OPTLINKER04_INFILESC0="..\h264dec\Release\h264dec.lib" "..\h264dec\Release\h264dec.obj" "..\h264dec\Release\lowlevel.obj" \
	"..\h264dec\Release\md5.obj" "..\h264dec\Release\my_getopt.obj" "..\h264dec\Release\resetprg.obj" \
	"..\h264dec\Release\sbrk.obj"
H264DEC_RELEASE_OPTLINKER04_OUTFILESC0="..\h264dec\Release\h264dec.mot" "..\h264dec\Release\h264dec.abs"
H264DEC_RELEASE_OPTLINKER04_DEPFILESC0="..\libm2dec\Release\libm2dec.lib"

#######################
# nmake "all" statement

ALL:	H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_ENVC0 \
	$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0) \
	$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1) \
	$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2) \
	$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3) \
	$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4) \
	$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5) \
	$(H264DEC_RELEASE_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Library Generator01 phase
!MESSAGE

H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\minegisi\AppData\Local\Temp

$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) : $(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-output="..\h264dec\Release\h264dec.lib"
-gbr=auto
-head=runtime,new,ctype,stdio,stdlib,string
<<

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC0) : "..\resetprg.c" $(H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC0)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\lib"
-object="..\h264dec\Release\resetprg.obj"
-debug
-gbr=auto
-macsave=0
"..\resetprg.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC1) : "..\sbrk.c" $(H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC1)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\lib"
-object="..\h264dec\Release\sbrk.obj"
-debug
-gbr=auto
-macsave=0
"..\sbrk.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC2) : "..\..\..\src\app\h264dec.cpp" $(H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC2)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Release\h264dec.obj"
-debug
-gbr=auto
-macsave=0
"..\..\..\src\app\h264dec.cpp"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=cpp
-nologo
<<

$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC3) : "..\..\..\src\app\lowlevel.c" $(H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC3)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Release\lowlevel.obj"
-debug
-gbr=auto
-macsave=0
"..\..\..\src\app\lowlevel.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC4) : "..\..\..\src\app\md5.c" $(H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC4)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Release\md5.obj"
-debug
-gbr=auto
-macsave=0
"..\..\..\src\app\md5.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(H264DEC_RELEASE_SH_CC_COMPILER02_OUTFILESC5) : "..\..\..\src\app\my_getopt.c" $(H264DEC_RELEASE_SH_CC_COMPILER02_DEPFILESC5)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh4aldsp
-endian=little
-bit_order=right
-include="$(TC_INSTALL_DIR)\include\stlport","..\..\..\src\app\..\lib"
-object="..\h264dec\Release\my_getopt.obj"
-debug
-gbr=auto
-macsave=0
"..\..\..\src\app\my_getopt.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(H264DEC_RELEASE_OPTLINKER04_OUTFILESC0) : $(H264DEC_RELEASE_OPTLINKER04_INFILESC0) $(H264DEC_RELEASE_OPTLINKER04_DEPFILESC0)
	"$(H264DEC_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(H264DEC_RELEASE_OPTLINKER04_EXE)" -subcommand=<<
nomessage 
list "..\h264dec\Release\h264dec.map"
show symbol,reference
nooptimize
-start=PBOOT,CBOOT/00,P,D,C,C$VTBL,CM2D,PM2D,PM2D_FAST,B/0C000000,BHEAP/0C080000,BFILES/0D880000
nologo
-stack
-input="..\h264dec\Release\h264dec.obj"
-input="..\h264dec\Release\lowlevel.obj"
-input="..\h264dec\Release\md5.obj"
-input="..\h264dec\Release\my_getopt.obj"
-input="..\h264dec\Release\resetprg.obj"
-input="..\h264dec\Release\sbrk.obj"
-library="..\libm2dec\Release\libm2dec.lib"
-library="..\h264dec\Release\h264dec.lib"
-output="..\h264dec\Release\h264dec.abs"
end
-input="..\h264dec\Release\h264dec.abs"
form stype
output "..\h264dec\Release\h264dec.mot"
-exit
<<


!ENDIF

!ENDIF

